import ObserverPatchHolography.CollarStates

/-!
# T2 modular-route receipts: the recast cannot force the collar clause

The T2 proposal recast the collar clause as "retained family ⊆ modular
centralizer of the boundary vacuum ω".  The paper read closed this as
RELOCATED + CIRCULAR: on the realized branch of `ax:maxent` the modular
Hamiltonian `K(λ) = Σ λ_a O_a` IS the retained family, so the dynamics
the construction supplies canonically is generated by the very choice
the clause was meant to constrain.  This file machine-checks the two
receipts of that closure, so the recast is not re-proposed as live:

* **Receipt 1 (naive recast is vacuous).**  The modular centralizer of
  a state is the commutant of its density.  For every realized-branch
  state `gibbsM SFam lam` of the non-central witness family
  `SFam = ![uuC, XXC]`, the genuinely non-central coupling `XXC` COMMUTES
  with the state (`XXC_commute_gibbs`) — the family commutes, so
  "retained ⊆ centralizer(ω)" is satisfied trivially by the very element
  the clause wants excluded.  A false receipt: compiles as a clause,
  excludes nothing.

* **Receipt 2 (corrected recast buys only the diagonal clause).**  To
  push `XXC` out of the centralizer, the modular Hamiltonian must break
  the `uuC`-eigenspace degeneracy with one-sided boundary charges
  `uLC = u⊗1`, `uRC = 1⊗u`.  But then the witness `w = uLC + uRC` is
  gauge-invariant, cross-cut, NOT flux — and still commutes with every
  one-sided-charge Gibbs state
  (`centralizer_diagonal_strictly_contains_flux`).  The corrected recast
  forces at most "retained ⊆ diagonal algebra span{1, uLC, uRC, uuC}",
  which strictly contains `FluxC`: WEAKER than the collar clause
  (cross-cut ⇒ flux).  The gap is one-sided-charge mixtures; closing it
  is a claim-weakening decision, not a derivation.

These are receipts ABOUT the relocation, not escapes from it.  They do
NOT close #544; "declare the clause" stays the honest floor (T2 fence).
-/

namespace OPH

open Kronecker Matrix

/-! ## Receipt 1 — the naive modular recast is vacuous

`XXC` commutes with every realized-branch Gibbs state of the retained
family, via the banked joint spectral basis: `XXC` commutes with `uuC`
(`uuC_comm_XXC`), hence with every `specProjP`, hence with the spectral
sum `gibbsM_spectral` term by term. -/

theorem XXC_comm_quP (s : Fin 2) : Commute XXC (quP s) := by
  have h : Commute XXC uuC := uuC_comm_XXC.symm
  rw [quP]
  exact ((Commute.one_right XXC).add_right (h.smul_right _)).smul_right _

theorem XXC_comm_qxP (t : Fin 2) : Commute XXC (qxP t) := by
  rw [qxP]
  exact ((Commute.one_right XXC).add_right
    ((Commute.refl XXC).smul_right _)).smul_right _

theorem XXC_comm_specProjP (p : Fin 2 × Fin 2) :
    Commute XXC (specProjP p) :=
  (XXC_comm_quP p.1).mul_right (XXC_comm_qxP p.2)

/-- The non-central coupling commutes with EVERY realized-branch state
    of the retained family — it sits inside the modular centralizer of
    every `ω` the recast can name on that branch. -/
theorem XXC_commute_gibbs (lam : Fin 2 → ℝ) :
    Commute XXC (gibbsM SFam lam) := by
  rw [gibbsM_spectral]
  exact Commute.sum_right _ _ _ fun p _ =>
    (XXC_comm_specProjP p).smul_right _

/-- **Receipt 1 — the naive recast is a false receipt.**  The witness
    `XXC` carries every credential the collar clause cares about
    (gauge-invariant, cross-cut, not flux) and still lies in the modular
    centralizer of every realized-branch state: "retained ⊆
    centralizer(ω)" is trivially satisfied by the non-central family and
    excludes nothing. -/
theorem naive_modular_recast_does_not_exclude :
    GaugeInvariantC XXC ∧ CrossCutC XXC ∧ XXC ∉ FluxC ∧
      ∀ lam : Fin 2 → ℝ, Commute XXC (gibbsM SFam lam) :=
  ⟨XXC_invariant, XXC_crossCut, XXC_notMem_fluxC, XXC_commute_gibbs⟩

/-! ## Receipt 2 — the corrected recast buys only the diagonal clause

One-sided boundary charges, built exactly like `uuC = u⊗u`, `XXC = X⊗X`
from the model's own half-collar embeddings. -/

/-- The left boundary charge `u ⊗ 1`. -/
noncomputable def uLC : CollarC := kronLeftC (uMat.map (Int.cast : ℤ → ℂ))

/-- The right boundary charge `1 ⊗ u`. -/
noncomputable def uRC : CollarC := kronRightC (uMat.map (Int.cast : ℤ → ℂ))

theorem uLC_eq_kron :
    uLC = (uMat.map (Int.cast : ℤ → ℂ)) ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ) :=
  rfl

theorem uRC_eq_kron :
    uRC = (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ (uMat.map (Int.cast : ℤ → ℂ)) :=
  rfl

theorem uMatC_sq :
    (uMat.map (Int.cast : ℤ → ℂ)) * (uMat.map (Int.cast : ℤ → ℂ)) = 1 := by
  have h : uMat * uMat = 1 := by decide
  have hcast : uMat.map (Int.cast : ℤ → ℂ) = uMat.map ⇑(Int.castRingHom ℂ) :=
    rfl
  rw [hcast, ← Matrix.map_mul, h]
  exact Matrix.map_one _ (map_zero _) (map_one _)

theorem uLC_mul_uRC : uLC * uRC = uuC := by
  rw [uLC_eq_kron, uRC_eq_kron, ← Matrix.mul_kronecker_mul, mul_one, one_mul,
    uuC_eq_kron]

theorem uRC_mul_uLC : uRC * uLC = uuC := by
  rw [uLC_eq_kron, uRC_eq_kron, ← Matrix.mul_kronecker_mul, mul_one, one_mul,
    uuC_eq_kron]

theorem uLC_comm_uRC : Commute uLC uRC := by
  show uLC * uRC = uRC * uLC
  rw [uLC_mul_uRC, uRC_mul_uLC]

theorem uuC_mul_uLC : uuC * uLC = uRC := by
  rw [uuC_eq_kron, uLC_eq_kron, ← Matrix.mul_kronecker_mul, uMatC_sq, mul_one,
    uRC_eq_kron]

theorem uLC_mul_uuC : uLC * uuC = uRC := by
  rw [uuC_eq_kron, uLC_eq_kron, ← Matrix.mul_kronecker_mul, uMatC_sq, one_mul,
    uRC_eq_kron]

theorem uuC_mul_uRC : uuC * uRC = uLC := by
  rw [uuC_eq_kron, uRC_eq_kron, ← Matrix.mul_kronecker_mul, uMatC_sq, mul_one,
    uLC_eq_kron]

theorem uRC_mul_uuC : uRC * uuC = uLC := by
  rw [uuC_eq_kron, uRC_eq_kron, ← Matrix.mul_kronecker_mul, uMatC_sq, one_mul,
    uLC_eq_kron]

/-- The one-sided-charge mixture: the witness of the diagonal/flux gap. -/
noncomputable def wMix : CollarC := uLC + uRC

theorem wMix_invariant : GaugeInvariantC wMix := by
  refine invariant_of_comm_uuC ?_
  rw [wMix, mul_add, add_mul, uuC_mul_uLC, uuC_mul_uRC, uLC_mul_uuC,
    uRC_mul_uuC, add_comm]

/-! Entry values of the witness (the four diagonal sectors used by the
non-membership arguments). -/

theorem uLC_apply (i j : Fin 2 × Fin 2) :
    uLC i j = ((uMat i.1 j.1 : ℤ) : ℂ)
      * (1 : Matrix (Fin 2) (Fin 2) ℂ) i.2 j.2 :=
  rfl

theorem uRC_apply (i j : Fin 2 × Fin 2) :
    uRC i j = (1 : Matrix (Fin 2) (Fin 2) ℂ) i.1 j.1
      * ((uMat i.2 j.2 : ℤ) : ℂ) :=
  rfl

theorem wMix_00 : wMix ((0 : Fin 2), (0 : Fin 2)) ((0 : Fin 2), (0 : Fin 2))
    = (2 : ℂ) := by
  have h : uMat 0 0 = 1 := by decide
  rw [wMix, Matrix.add_apply, uLC_apply, uRC_apply, h]
  norm_num [Matrix.one_apply]

theorem wMix_0101 : wMix ((0 : Fin 2), (1 : Fin 2)) ((0 : Fin 2), (1 : Fin 2))
    = (0 : ℂ) := by
  have h0 : uMat 0 0 = 1 := by decide
  have h1 : uMat 1 1 = -1 := by decide
  rw [wMix, Matrix.add_apply, uLC_apply, uRC_apply, h0, h1]
  norm_num [Matrix.one_apply]

theorem wMix_1010 : wMix ((1 : Fin 2), (0 : Fin 2)) ((1 : Fin 2), (0 : Fin 2))
    = (0 : ℂ) := by
  have h0 : uMat 0 0 = 1 := by decide
  have h1 : uMat 1 1 = -1 := by decide
  rw [wMix, Matrix.add_apply, uLC_apply, uRC_apply, h0, h1]
  norm_num [Matrix.one_apply]

theorem wMix_1111 : wMix ((1 : Fin 2), (1 : Fin 2)) ((1 : Fin 2), (1 : Fin 2))
    = (-2 : ℂ) := by
  have h1 : uMat 1 1 = -1 := by decide
  rw [wMix, Matrix.add_apply, uLC_apply, uRC_apply, h1]
  norm_num [Matrix.one_apply]

theorem wMix_notMem_MLC : wMix ∉ modelLayerC.ML := by
  rintro ⟨m, hm⟩
  have h1 : m 0 0 * (1 : Matrix (Fin 2) (Fin 2) ℂ) 0 0
      = wMix ((0 : Fin 2), (0 : Fin 2)) ((0 : Fin 2), (0 : Fin 2)) :=
    congrFun (congrFun hm ((0 : Fin 2), (0 : Fin 2))) ((0 : Fin 2), (0 : Fin 2))
  have h2 : m 0 0 * (1 : Matrix (Fin 2) (Fin 2) ℂ) 1 1
      = wMix ((0 : Fin 2), (1 : Fin 2)) ((0 : Fin 2), (1 : Fin 2)) :=
    congrFun (congrFun hm ((0 : Fin 2), (1 : Fin 2))) ((0 : Fin 2), (1 : Fin 2))
  rw [wMix_00] at h1
  rw [wMix_0101] at h2
  simp only [Matrix.one_apply_eq, mul_one] at h1 h2
  rw [h2] at h1
  norm_num at h1

theorem wMix_notMem_MRC : wMix ∉ modelLayerC.MR := by
  rintro ⟨n, hn⟩
  have h1 : (1 : Matrix (Fin 2) (Fin 2) ℂ) 0 0 * n 0 0
      = wMix ((0 : Fin 2), (0 : Fin 2)) ((0 : Fin 2), (0 : Fin 2)) :=
    congrFun (congrFun hn ((0 : Fin 2), (0 : Fin 2))) ((0 : Fin 2), (0 : Fin 2))
  have h2 : (1 : Matrix (Fin 2) (Fin 2) ℂ) 1 1 * n 0 0
      = wMix ((1 : Fin 2), (0 : Fin 2)) ((1 : Fin 2), (0 : Fin 2)) :=
    congrFun (congrFun hn ((1 : Fin 2), (0 : Fin 2))) ((1 : Fin 2), (0 : Fin 2))
  rw [wMix_00] at h1
  rw [wMix_1010] at h2
  simp only [Matrix.one_apply_eq, one_mul] at h1 h2
  rw [h2] at h1
  norm_num at h1

theorem wMix_crossCut : CrossCutC wMix := by
  rintro (h | h)
  · exact wMix_notMem_MLC h
  · exact wMix_notMem_MRC h

/-- The ℂ-span of `{1, uuC}` is a subring (`uuC² = 1` closes
    multiplication) — the flux hull used to bound `K = ⟨uuC⟩`. -/
def fluxSpanT2C : Subring CollarC where
  carrier := {m | ∃ a b : ℂ, m = a • 1 + b • uuC}
  zero_mem' := ⟨0, 0, by simp⟩
  one_mem' := ⟨1, 0, by simp⟩
  add_mem' := by
    rintro x y ⟨a1, b1, rfl⟩ ⟨a2, b2, rfl⟩
    exact ⟨a1 + a2, b1 + b2, by module⟩
  neg_mem' := by
    rintro x ⟨a1, b1, rfl⟩
    exact ⟨-a1, -b1, by module⟩
  mul_mem' := by
    rintro x y ⟨a1, b1, rfl⟩ ⟨a2, b2, rfl⟩
    refine ⟨a1 * a2 + b1 * b2, a1 * b2 + b1 * a2, ?_⟩
    rw [add_mul, mul_add, mul_add, smul_mul_smul_comm, smul_mul_smul_comm,
      smul_mul_smul_comm, smul_mul_smul_comm, uuC_sq]
    simp only [one_mul, mul_one]
    module

theorem uuC_00 : uuC ((0 : Fin 2), (0 : Fin 2)) ((0 : Fin 2), (0 : Fin 2))
    = (1 : ℂ) := by
  have h : uu ((0 : Fin 2), (0 : Fin 2)) ((0 : Fin 2), (0 : Fin 2)) = 1 := by
    decide
  show ((uu _ _ : ℤ) : ℂ) = 1
  rw [h, Int.cast_one]

theorem uuC_1111 : uuC ((1 : Fin 2), (1 : Fin 2)) ((1 : Fin 2), (1 : Fin 2))
    = (1 : ℂ) := by
  have h : uu ((1 : Fin 2), (1 : Fin 2)) ((1 : Fin 2), (1 : Fin 2)) = 1 := by
    decide
  show ((uu _ _ : ℤ) : ℂ) = 1
  rw [h, Int.cast_one]

/-- The one-sided-charge mixture is NOT a flux term: it is diagonal and
    invariant, but its two `uuC`-sector diagonal values differ in sign,
    which no element of `span{1, uuC}` can do. -/
theorem wMix_notMem_fluxC : wMix ∉ FluxC := by
  rintro ⟨hK, -⟩
  have hle : Subring.closure {uuC} ≤ fluxSpanT2C := by
    rw [Subring.closure_le]
    intro g hg
    rw [Set.mem_singleton_iff] at hg
    subst hg
    exact ⟨0, 1, by simp⟩
  obtain ⟨a, b, hab⟩ := hle hK
  have e1 := congrFun (congrFun hab ((0 : Fin 2), (0 : Fin 2)))
    ((0 : Fin 2), (0 : Fin 2))
  have e2 := congrFun (congrFun hab ((1 : Fin 2), (1 : Fin 2)))
    ((1 : Fin 2), (1 : Fin 2))
  rw [wMix_00] at e1
  rw [wMix_1111] at e2
  simp only [Matrix.add_apply, Matrix.smul_apply, Matrix.one_apply_eq,
    smul_eq_mul, mul_one, uuC_00, uuC_1111] at e1 e2
  have h := e1.trans e2.symm
  norm_num at h

/-! ### The witness commutes with every one-sided-charge Gibbs state -/

theorem wMix_comm_uLC : Commute wMix uLC :=
  (Commute.refl uLC).add_left uLC_comm_uRC.symm

theorem wMix_comm_uRC : Commute wMix uRC :=
  uLC_comm_uRC.add_left (Commute.refl uRC)

open NormedSpace in
/-- The mixture commutes with every Gibbs state of the one-sided-charge
    family — the corrected modular Hamiltonian cannot push it out of the
    centralizer either. -/
theorem wMix_commute_gibbs_oneSided (lam : Fin 2 → ℝ) :
    Commute wMix (gibbsM ![uLC, uRC] lam) := by
  have harg : Commute wMix
      (-(∑ a : Fin 2, ((lam a : ℝ) : ℂ) • (![uLC, uRC] : Fin 2 → CollarC) a)) := by
    refine (Commute.sum_right _ _ _ fun i _ => ?_).neg_right
    fin_cases i
    · simpa using wMix_comm_uLC.smul_right (((lam 0 : ℝ) : ℂ))
    · simpa using wMix_comm_uRC.smul_right (((lam 1 : ℝ) : ℂ))
  rw [gibbsM]
  exact harg.exp_right.smul_right _

/-- **Receipt 2 — the corrected recast forces at most the DIAGONAL
    clause.**  Even when the modular Hamiltonian is rebuilt from the
    one-sided boundary charges (the only way to break the
    `uuC`-eigenspace degeneracy), there is a witness — the mixture
    `uLC + uRC` — that is gauge-invariant, cross-cut, NOT flux, and
    still commutes with every such Gibbs state.  So the centralizer
    contains the full diagonal algebra `span{1, uLC, uRC, uuC}`, a
    STRICT superset of `FluxC`: the recast can force "retained ⊆
    diagonal", never the collar clause "cross-cut ⇒ flux".  The gap is
    exactly the one-sided-charge mixtures. -/
theorem centralizer_diagonal_strictly_contains_flux :
    ∃ w : CollarC, GaugeInvariantC w ∧ CrossCutC w ∧ w ∉ FluxC ∧
      ∀ lam : Fin 2 → ℝ, Commute w (gibbsM ![uLC, uRC] lam) :=
  ⟨wMix, wMix_invariant, wMix_crossCut, wMix_notMem_fluxC,
    wMix_commute_gibbs_oneSided⟩

/-! ## Axiom audit

Expected footprint for every entry: `[propext, Classical.choice,
Quot.sound]`.  No `sorry`, no `native_decide`, no extra axioms. -/

#print axioms XXC_commute_gibbs
#print axioms naive_modular_recast_does_not_exclude
#print axioms uLC_mul_uRC
#print axioms wMix_invariant
#print axioms wMix_crossCut
#print axioms wMix_notMem_fluxC
#print axioms wMix_commute_gibbs_oneSided
#print axioms centralizer_diagonal_strictly_contains_flux

end OPH
