import ObserverPatchHolography.CollarStates

/-!
# T2 modular-route receipts: the recast cannot force the collar clause

The T2 proposal recast the collar clause as "retained family ⊆ modular
centralizer of the boundary vacuum ω".  The paper read closed this as
RELOCATED + CIRCULAR: on the realized branch of `ax:maxent` the modular
Hamiltonian `K(λ) = Σ λ_a O_a` IS the retained family, so the dynamics
the construction supplies canonically is generated by the very choice
the clause was meant to constrain.  This file machine-checks the two
receipts of that closure, so the recast is not re-proposed as live:

* **Receipt 1 (naive recast is vacuous).**  The modular centralizer of
  a state is the commutant of its density.  For every realized-branch
  state `gibbsM SFam lam` of the non-central witness family
  `SFam = ![uuC, XXC]`, the genuinely non-central coupling `XXC` COMMUTES
  with the state (`XXC_commute_gibbs`) — the family commutes, so
  "retained ⊆ centralizer(ω)" is satisfied trivially by the very element
  the clause wants excluded.  A false receipt: compiles as a clause,
  excludes nothing.

* **Receipt 2 (corrected recast buys only the diagonal clause).**  To
  push `XXC` out of the centralizer, the modular Hamiltonian must break
  the `uuC`-eigenspace degeneracy with one-sided boundary charges
  `uLC = u⊗1`, `uRC = 1⊗u`.  But then the witness `w = uLC + uRC` is
  gauge-invariant, cross-cut, NOT flux — and still commutes with every
  one-sided-charge Gibbs state
  (`centralizer_diagonal_strictly_contains_flux`).  The corrected recast
  forces at most "retained ⊆ diagonal algebra span{1, uLC, uRC, uuC}",
  which strictly contains `FluxC`: WEAKER than the collar clause
  (cross-cut ⇒ flux).  The gap is one-sided-charge mixtures; closing it
  is a claim-weakening decision, not a derivation.

These are receipts ABOUT the relocation, not escapes from it.  They do
NOT close #544; "declare the clause" stays the honest floor (T2 fence).
-/

namespace OPH

open Kronecker Matrix

/-! ## Receipt 1 — the naive modular recast is vacuous

`XXC` commutes with every realized-branch Gibbs state of the retained
family, via the banked joint spectral basis: `XXC` commutes with `uuC`
(`uuC_comm_XXC`), hence with every `specProjP`, hence with the spectral
sum `gibbsM_spectral` term by term. -/

theorem XXC_comm_quP (s : Fin 2) : Commute XXC (quP s) := by
  have h : Commute XXC uuC := uuC_comm_XXC.symm
  rw [quP]
  exact ((Commute.one_right XXC).add_right (h.smul_right _)).smul_right _

theorem XXC_comm_qxP (t : Fin 2) : Commute XXC (qxP t) := by
  rw [qxP]
  exact ((Commute.one_right XXC).add_right
    ((Commute.refl XXC).smul_right _)).smul_right _

theorem XXC_comm_specProjP (p : Fin 2 × Fin 2) :
    Commute XXC (specProjP p) :=
  (XXC_comm_quP p.1).mul_right (XXC_comm_qxP p.2)

/-- The non-central coupling commutes with EVERY realized-branch state
    of the retained family — it sits inside the modular centralizer of
    every `ω` the recast can name on that branch. -/
theorem XXC_commute_gibbs (lam : Fin 2 → ℝ) :
    Commute XXC (gibbsM SFam lam) := by
  rw [gibbsM_spectral]
  exact Commute.sum_right _ _ _ fun p _ =>
    (XXC_comm_specProjP p).smul_right _

/-- **Receipt 1 — the naive recast is a false receipt.**  The witness
    `XXC` carries every credential the collar clause cares about
    (gauge-invariant, cross-cut, not flux) and still lies in the modular
    centralizer of every realized-branch state: "retained ⊆
    centralizer(ω)" is trivially satisfied by the non-central family and
    excludes nothing. -/
theorem naive_modular_recast_does_not_exclude :
    GaugeInvariantC XXC ∧ CrossCutC XXC ∧ XXC ∉ FluxC ∧
      ∀ lam : Fin 2 → ℝ, Commute XXC (gibbsM SFam lam) :=
  ⟨XXC_invariant, XXC_crossCut, XXC_notMem_fluxC, XXC_commute_gibbs⟩
/-! ## Axiom audit (Receipt 1)

Expected footprint: `[propext, Classical.choice, Quot.sound]`. -/

#print axioms XXC_commute_gibbs
#print axioms naive_modular_recast_does_not_exclude

end OPH
