import Mathlib.Algebra.Group.Action.Pointwise.Set.Basic
import Mathlib.Data.Set.Card
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.GroupTheory.SpecificGroups.Alternating
import Mathlib.GroupTheory.Perm.Fin

/-!
# The icosahedral anti-bridge: no A5-invariant 8+3+1 split of 12

OPH's "number 12" narrative identifies the 12 icosahedral curvature
defects with the 12 Standard-Model gauge generators
(8 gluons + 3 weak + 1 photon).  The icosahedral rotation group is
`A5 ≅ alternatingGroup (Fin 5)`, and it acts **transitively** on the 12
vertices.  This file machine-checks the anti-bridge fact:

  a transitive group action admits NO invariant partition of its
  12-element space into blocks of sizes 8, 3, 1,

so the naive defect ↔ generator correspondence cannot be
`A5`-equivariant.  (At the representation level the same wall appears:
the irreducible representations of `A5` have dimensions {1, 3, 3′, 4, 5}
— there is no 8 for a gluon octet; that remark stays prose.)

Contents:

* **General core** — for any pretransitive action, an invariant set is
  `∅` or `univ` (`invariant_set_eq_empty_or_univ`), hence no invariant
  set of intermediate cardinality (`no_proper_invariant_set`), hence no
  invariant 8+3+1 partition of a 12-element space
  (`no_invariant_8_3_1_of_pretransitive`).
* **Concrete instance** — a transitive `A5`-action on a genuine
  12-element space: the coset space `A5 ⧸ H5` for the order-5 subgroup
  `H5 = zpowers rot5` generated by the explicit even 5-cycle
  `finRotate 5` (`card_defectSpace : Nat.card DefectSpace = 12`).
  This is the abstract model of the icosahedral vertex action
  (vertex stabilizers are the order-5 rotation subgroups).
* **The receipt** — `oph_defect_generator_not_A5_equivariant`: no
  `A5`-invariant partition of `DefectSpace` into blocks 8+3+1.

Claim discipline: this proves the naive defect–generator map cannot be
`A5`-equivariant.  It does NOT refute OPH; it names the
defect–generator correspondence as an honest physical postulate rather
than a consequence of icosahedral symmetry.
-/

namespace OPH

open MulAction
open scoped Pointwise

/-! ## General core: pretransitive actions have no proper invariant sets -/

section Core

variable {G α : Type*} [Group G] [MulAction G α] [IsPretransitive G α]

/-- Under a pretransitive action, an invariant set is empty or
    everything. -/
theorem invariant_set_eq_empty_or_univ (S : Set α)
    (hS : ∀ g : G, g • S = S) : S = ∅ ∨ S = Set.univ := by
  rcases S.eq_empty_or_nonempty with h | ⟨a, ha⟩
  · exact Or.inl h
  · refine Or.inr (Set.eq_univ_of_forall fun b => ?_)
    obtain ⟨g, hg⟩ := MulAction.exists_smul_eq G a b
    rw [← hS g]
    exact ⟨a, ha, hg⟩

/-- Under a pretransitive action there is no invariant set of
    intermediate size: `0 < |S| < |α|` is impossible. -/
theorem no_proper_invariant_set (S : Set α) (hS : ∀ g : G, g • S = S)
    (h0 : 0 < S.ncard) (hlt : S.ncard < Nat.card α) : False := by
  rcases invariant_set_eq_empty_or_univ S hS with h | h
  · rw [h, Set.ncard_empty] at h0
    exact lt_irrefl 0 h0
  · rw [h, Set.ncard_univ] at hlt
    exact lt_irrefl _ hlt

/-- **No invariant 8+3+1 partition of a transitive 12.**  If a group
    acts pretransitively on a 12-element space, there is no invariant
    partition into blocks of sizes 8, 3, 1: already the size-8 block is
    an invariant set of intermediate cardinality.  The unused blocks are
    carried in the signature so the statement reads as the full
    gluon/weak/photon split. -/
theorem no_invariant_8_3_1_of_pretransitive (hcard : Nat.card α = 12)
    (A B C : Set α)
    (hA : ∀ g : G, g • A = A)
    (_hB : ∀ g : G, g • B = B)
    (_hC : ∀ g : G, g • C = C)
    (hA8 : A.ncard = 8) (_hB3 : B.ncard = 3) (_hC1 : C.ncard = 1) :
    False :=
  no_proper_invariant_set A hA
    (by rw [hA8]; norm_num)
    (by rw [hA8, hcard]; norm_num)

end Core

/-! ## The concrete transitive 12: `A5` on the coset space of an
order-5 subgroup -/

/-- The icosahedral rotation group, presented as `A5`. -/
abbrev A5 := alternatingGroup (Fin 5)

/-- The explicit even 5-cycle `finRotate 5` as an element of `A5`
    (`sign (finRotate 5) = (-1)^4 = 1`). -/
def rot5 : A5 :=
  ⟨finRotate 5, by
    rw [Equiv.Perm.mem_alternatingGroup, sign_finRotate]
    decide⟩

theorem orderOf_rot5 : orderOf rot5 = 5 := by
  rw [rot5, Subgroup.orderOf_mk, (isCycle_finRotate (n := 3)).orderOf,
    support_finRotate, Finset.card_univ, Fintype.card_fin]

/-- The order-5 subgroup generated by the 5-cycle — the abstract vertex
    stabilizer. -/
def H5 : Subgroup A5 := Subgroup.zpowers rot5

/-- The 12-element homogeneous space `A5 ⧸ H5` — the abstract model of
    the icosahedral vertex set with its transitive `A5`-action
    (Mathlib provides the action and its pretransitivity). -/
abbrev DefectSpace := A5 ⧸ H5

theorem nat_card_A5 : Nat.card A5 = 60 := by
  rw [A5, nat_card_alternatingGroup, Nat.card_eq_fintype_card,
    Fintype.card_fin]
  norm_num [Nat.factorial]

theorem card_H5 : Nat.card H5 = 5 := by
  rw [H5, Nat.card_zpowers, orderOf_rot5]

/-- The homogeneous space has exactly 12 points: `60 / 5`. -/
theorem card_defectSpace : Nat.card DefectSpace = 12 := by
  have hprod := Subgroup.card_mul_index (H := H5)
  rw [card_H5, nat_card_A5] at hprod
  have hidx : H5.index = Nat.card DefectSpace := rfl
  omega

/-! ## The anti-bridge receipt -/

/-- **The OPH anti-bridge NO-GO.**  On the 12-point homogeneous
    icosahedral space there is no `A5`-invariant partition into blocks
    of sizes 8, 3, 1 — the naive correspondence between the 12
    curvature defects and the 8+3+1 Standard-Model gauge generators
    cannot be `A5`-equivariant.  `A5` is transitive on the 12, so the
    would-be gluon block of size 8 already contradicts
    `no_proper_invariant_set`.

    This does not refute the OPH framework; it certifies that its
    defect–generator correspondence is a physical postulate, not a
    consequence of icosahedral symmetry. -/
theorem oph_defect_generator_not_A5_equivariant
    (A B C : Set DefectSpace)
    (hA : ∀ g : A5, g • A = A)
    (hB : ∀ g : A5, g • B = B)
    (hC : ∀ g : A5, g • C = C)
    (hA8 : A.ncard = 8) (hB3 : B.ncard = 3) (hC1 : C.ncard = 1) :
    False :=
  no_invariant_8_3_1_of_pretransitive card_defectSpace A B C hA hB hC
    hA8 hB3 hC1

/-! ## Axiom audit

Expected footprint for every entry: `[propext, Classical.choice,
Quot.sound]`.  No `sorry`, no `native_decide`, no extra axioms. -/

#print axioms invariant_set_eq_empty_or_univ
#print axioms no_proper_invariant_set
#print axioms no_invariant_8_3_1_of_pretransitive
#print axioms orderOf_rot5
#print axioms nat_card_A5
#print axioms card_H5
#print axioms card_defectSpace
#print axioms oph_defect_generator_not_A5_equivariant

end OPH
