import Mathlib.Algebra.Group.Action.Pointwise.Set.Basic
import Mathlib.Data.Set.Card
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.GroupTheory.SpecificGroups.Alternating
import Mathlib.GroupTheory.Perm.Fin

/-!
# The icosahedral anti-bridge: no A5-invariant 8+3+1 split of 12

OPH's "number 12" narrative identifies the 12 icosahedral curvature
defects with the 12 Standard-Model gauge generators
(8 gluons + 3 weak + 1 photon).  The icosahedral rotation group is
`A5 ≅ alternatingGroup (Fin 5)`, and it acts **transitively** on the 12
vertices.  This file machine-checks the anti-bridge fact:

  a transitive group action admits NO invariant partition of its
  12-element space into blocks of sizes 8, 3, 1,

so the naive defect ↔ generator correspondence cannot be
`A5`-equivariant.  (At the representation level the same wall appears:
the irreducible representations of `A5` have dimensions {1, 3, 3′, 4, 5}
— there is no 8 for a gluon octet; that remark stays prose.)

Contents:

* **General core** — for any pretransitive action, an invariant set is
  `∅` or `univ` (`invariant_set_eq_empty_or_univ`), hence no invariant
  set of intermediate cardinality (`no_proper_invariant_set`), hence no
  invariant 8+3+1 partition of a 12-element space
  (`no_invariant_8_3_1_of_pretransitive`).
* **Concrete instance** — a transitive `A5`-action on a genuine
  12-element space: the coset space `A5 ⧸ H5` for the order-5 subgroup
  `H5 = zpowers rot5` generated by the explicit even 5-cycle
  `finRotate 5` (`card_defectSpace : Nat.card DefectSpace = 12`).
  This is the abstract model of the icosahedral vertex action
  (vertex stabilizers are the order-5 rotation subgroups).
* **The receipt** — `oph_defect_generator_not_A5_equivariant`: no
  `A5`-invariant partition of `DefectSpace` into blocks 8+3+1.

Claim discipline: this proves the naive defect–generator map cannot be
`A5`-equivariant.  It does NOT refute OPH; it names the
defect–generator correspondence as an honest physical postulate rather
than a consequence of icosahedral symmetry.
-/

namespace OPH

open MulAction
open scoped Pointwise

/-! ## General core: pretransitive actions have no proper invariant sets -/

section Core

variable {G α : Type*} [Group G] [MulAction G α] [IsPretransitive G α]

/-- Under a pretransitive action, an invariant set is empty or
    everything. -/
theorem invariant_set_eq_empty_or_univ (S : Set α)
    (hS : ∀ g : G, g • S = S) : S = ∅ ∨ S = Set.univ := by
  rcases S.eq_empty_or_nonempty with h | ⟨a, ha⟩
  · exact Or.inl h
  · refine Or.inr (Set.eq_univ_of_forall fun b => ?_)
    obtain ⟨g, hg⟩ := MulAction.exists_smul_eq G a b
    rw [← hS g]
    exact ⟨a, ha, hg⟩

/-- Under a pretransitive action there is no invariant set of
    intermediate size: `0 < |S| < |α|` is impossible. -/
theorem no_proper_invariant_set (S : Set α) (hS : ∀ g : G, g • S = S)
    (h0 : 0 < S.ncard) (hlt : S.ncard < Nat.card α) : False := by
  rcases invariant_set_eq_empty_or_univ S hS with h | h
  · rw [h, Set.ncard_empty] at h0
    exact lt_irrefl 0 h0
  · rw [h, Set.ncard_univ] at hlt
    exact lt_irrefl _ hlt

/-- **No invariant 8+3+1 partition of a transitive 12.**  If a group
    acts pretransitively on a 12-element space, there is no invariant
    partition into blocks of sizes 8, 3, 1: already the size-8 block is
    an invariant set of intermediate cardinality.  The unused blocks are
    carried in the signature so the statement reads as the full
    gluon/weak/photon split. -/
theorem no_invariant_8_3_1_of_pretransitive (hcard : Nat.card α = 12)
    (A B C : Set α)
    (hA : ∀ g : G, g • A = A)
    (_hB : ∀ g : G, g • B = B)
    (_hC : ∀ g : G, g • C = C)
    (hA8 : A.ncard = 8) (_hB3 : B.ncard = 3) (_hC1 : C.ncard = 1) :
    False :=
  no_proper_invariant_set A hA
    (by rw [hA8]; norm_num)
    (by rw [hA8, hcard]; norm_num)

end Core
/-! ## Axiom audit (core)

Expected footprint: `[propext, Classical.choice, Quot.sound]`. -/

#print axioms invariant_set_eq_empty_or_univ
#print axioms no_proper_invariant_set
#print axioms no_invariant_8_3_1_of_pretransitive

end OPH
